2020-09-07 at 16:33:33 | ERROR | Traceback (most recent call last):
  File "/database/dwd_news_yq/bin/process_data.py", line 934, in thread_process_data
    relation_path(company=relativity_company,db=db1,yqid=uid,ctimeDate=ctimeDate,emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,quancheng_list=quancheng_list,jiancheng_list=jiancheng_list,code_list=code_list,relScore=relativity,relLabel=relLabel,eventCode=eventCode,eventName=eventName,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content)
  File "/database/dwd_news_yq/bin/process_helper.py", line 1227, in relation_path
    r = requests.post('http://192.168.1.129:11068/relation/',data=json.dumps({'company':relativity_company.replace('(','（').replace(')','）')}))
UnboundLocalError: local variable 'relativity_company' referenced before assignment

2020-09-07 at 16:33:34 | ERROR | 处理报错消息内容:{'spider_name': 'caijing_eastmoney_xinsanban_all', 'collection_name': 'sy_news_finance_eastmoney_raw', 'start_time': '1599026544', 'end_time': '1599026635'}  消息处理总量:20条
2020-09-07 at 16:34:45 | ERROR | Traceback (most recent call last):
  File "/database/dwd_news_yq/bin/process_data.py", line 934, in thread_process_data
    relation_path(relativity_company=relativity_company,db=db1,yqid=uid,ctimeDate=ctimeDate,emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,quancheng_list=quancheng_list,jiancheng_list=jiancheng_list,code_list=code_list,relScore=relativity,relLabel=relLabel,eventCode=eventCode,eventName=eventName,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content)
  File "/database/dwd_news_yq/bin/process_helper.py", line 1245, in relation_path
    insert_statistics(db=db1,yqid=uid,company=relativity_company.replace('(','（').replace(')','）'),ctimeDate=ctimeDate,relType='传导关联',emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName)
NameError: name 'db1' is not defined

2020-09-07 at 16:34:46 | ERROR | 处理报错消息内容:{'start_time': '1599026544', 'spider_name': 'caijing_eastmoney_xinsanban_all', 'end_time': '1599026635', 'collection_name': 'sy_news_finance_eastmoney_raw'}  消息处理总量:20条
2020-09-07 at 16:35:17 | ERROR | Traceback (most recent call last):
  File "/database/dwd_news_yq/bin/process_data.py", line 934, in thread_process_data
    relation_path(relativity_company=relativity_company,db1=db1,yqid=uid,ctimeDate=ctimeDate,emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,quancheng_list=quancheng_list,jiancheng_list=jiancheng_list,code_list=code_list,relScore=relativity,relLabel=relLabel,eventCode=eventCode,eventName=eventName,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content)
TypeError: relation_path() got an unexpected keyword argument 'db1'

2020-09-07 at 16:35:17 | ERROR | 处理报错消息内容:{'collection_name': 'sy_news_finance_eastmoney_raw', 'end_time': '1599026635', 'spider_name': 'caijing_eastmoney_xinsanban_all', 'start_time': '1599026544'}  消息处理总量:20条
2020-09-07 at 16:47:53 | ERROR | Traceback (most recent call last):
  File "/database/dwd_news_yq/bin/process_data.py", line 934, in thread_process_data
    relation_path(relativity_company=relativity_company,db1=db1,yqid=uid,ctimeDate=ctimeDate,emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,quancheng_list=quancheng_list,jiancheng_list=jiancheng_list,code_list=code_list,relScore=relativity,relLabel=relLabel,eventCode=eventCode,eventName=eventName,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content)
  File "/database/dwd_news_yq/bin/process_helper.py", line 1245, in relation_path
    insert_statistics(db=db1,yqid=uid,company=relativity_company.replace('(','（').replace(')','）'),ctimeDate=ctimeDate,relType='传导关联',emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName)
NameError: name 'uid' is not defined

2020-09-07 at 16:47:54 | ERROR | 处理报错消息内容:{'collection_name': 'sy_news_finance_eastmoney_raw', 'spider_name': 'caijing_eastmoney_xinsanban_all', 'start_time': '1599026544', 'end_time': '1599026635'}  消息处理总量:20条
2020-09-07 at 16:48:30 | ERROR | Traceback (most recent call last):
  File "/database/dwd_news_yq/bin/process_data.py", line 934, in thread_process_data
    relation_path(relativity_company=relativity_company,db1=db1,uid=uid,ctimeDate=ctimeDate,emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,quancheng_list=quancheng_list,jiancheng_list=jiancheng_list,code_list=code_list,relScore=relativity,relLabel=relLabel,eventCode=eventCode,eventName=eventName,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content)
  File "/database/dwd_news_yq/bin/process_helper.py", line 1247, in relation_path
    insert_news_search(db=db1,yqid=uid,objName=company,companyShortName=relativity_companyShortName.replace('(','（').replace(')','）'),companyCode=relativity_companyCode,indirectObjName=relativity_company.replace('(','（').replace(')','）'),transScore=relativity_score,relPath=relPath,relType='传导关联',relScore=relativity,relLabel=relLabel,personName='',eventCode=eventCode,eventName=eventName,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,emoLabel=emoLabel,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content,isValid=1,dataStatus=1)
NameError: name 'relativity' is not defined

2020-09-07 at 16:48:30 | ERROR | 处理报错消息内容:{'end_time': '1599026635', 'collection_name': 'sy_news_finance_eastmoney_raw', 'spider_name': 'caijing_eastmoney_xinsanban_all', 'start_time': '1599026544'}  消息处理总量:20条
2020-09-07 at 16:49:27 | ERROR | Traceback (most recent call last):
  File "/database/dwd_news_yq/bin/process_data.py", line 934, in thread_process_data
    relation_path(relativity_company=relativity_company,db1=db1,uid=uid,ctimeDate=ctimeDate,emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,quancheng_list=quancheng_list,jiancheng_list=jiancheng_list,code_list=code_list,relativity=relativity,relLabel=relLabel,eventCode=eventCode,eventName=eventName,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content)
  File "/database/dwd_news_yq/bin/process_helper.py", line 1247, in relation_path
    insert_news_search(db=db1,yqid=uid,objName=company,companyShortName=relativity_companyShortName.replace('(','（').replace(')','）'),companyCode=relativity_companyCode,indirectObjName=relativity_company.replace('(','（').replace(')','）'),transScore=relativity_score,relPath=relPath,relType='传导关联',relScore=relativity,relLabel=relLabel,personName='',eventCode=eventCode,eventName=eventName,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,emoLabel=emoLabel,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content,isValid=1,dataStatus=1)
NameError: name 'importanceDgree' is not defined

2020-09-07 at 16:49:28 | ERROR | 处理报错消息内容:{'collection_name': 'sy_news_finance_eastmoney_raw', 'end_time': '1599026635', 'start_time': '1599026544', 'spider_name': 'caijing_eastmoney_xinsanban_all'}  消息处理总量:20条
2020-09-07 at 16:49:58 | ERROR | Traceback (most recent call last):
  File "/database/dwd_news_yq/bin/process_data.py", line 934, in thread_process_data
    relation_path(relativity_company=relativity_company,db1=db1,uid=uid,ctimeDate=ctimeDate,emoLabel=emoLabel,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,quancheng_list=quancheng_list,jiancheng_list=jiancheng_list,code_list=code_list,relativity=relativity,relLabel=relLabel,eventCode=eventCode,eventName=eventName,emoScore=emoScore,emoConf=emoConf,importanceDgree=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content)
  File "/database/dwd_news_yq/bin/process_helper.py", line 1247, in relation_path
    insert_news_search(db=db1,yqid=uid,objName=company,companyShortName=relativity_companyShortName.replace('(','（').replace(')','）'),companyCode=relativity_companyCode,indirectObjName=relativity_company.replace('(','（').replace(')','）'),transScore=relativity_score,relPath=relPath,relType='传导关联',relScore=relativity,relLabel=relLabel,personName='',eventCode=eventCode,eventName=eventName,firstLevelCode=firstLevelCode,firstLevelName=firstLevelName,secondLevelCode=secondLevelCode,secondLevelName=secondLevelName,thirdLevelCode=thirdLevelCode,thirdLevelName=thirdLevelName,fourthLevelCode=fourthLevelCode,fourthLevelName=fourthLevelName,emoLabel=emoLabel,emoScore=emoScore,emoConf=emoConf,impScore=importanceDgree,impLabel=importanceLabel,pubTime=ctime,title=title,summary=summary,keyword=keyword,srcUrl=url,srcType='新闻',source=source,content=search_content,isValid=1,dataStatus=1)
NameError: name 'importanceLabel' is not defined

2020-09-07 at 16:49:59 | ERROR | 处理报错消息内容:{'start_time': '1599026544', 'spider_name': 'caijing_eastmoney_xinsanban_all', 'collection_name': 'sy_news_finance_eastmoney_raw', 'end_time': '1599026635'}  消息处理总量:20条
2020-09-07 at 16:51:42 | ERROR | Traceback (most recent call last):
  File "consumer.py", line 26, in callback
    return Processing(msg).process_data(channel, method)
  File "/database/dwd_news_yq/bin/process_data.py", line 1001, in process_data
    time.sleep(1)
KeyboardInterrupt

